# Generated by Django 2.2.16 on 2024-06-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20240220_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок'),
        ),
    ]
