# Generated by Django 3.1 on 2024-06-19 13:13

from django.db import migrations
import posts.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=posts.fields.WEBPField(blank=True, upload_to='posts/', verbose_name='Картинка'),
        ),
    ]
