# Generated by Django 5.1 on 2024-08-30 12:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_follow_id_alter_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="follow",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата подписки",
            ),
            preserve_default=False,
        ),
    ]
